INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (166, null, '$$ x = 5 $$', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (167, null, '', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (168, null, '', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (169, null, '', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (170, null, '$$ x = 3 $$', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (171, null, '', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (172, null, '', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (176, null, '', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (177, null, '$$ x_1 = 0 $$
$$ x_2 = -1 $$', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (178, null, '', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (179, null, '', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (180, null, '$$ x = 2 $$', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (181, null, '', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (219, null, '', 0, '', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (221, 220, null, 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (222, 220, null, 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (223, 220, null, 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (224, 220, null, 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (225, 220, null, 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (226, 220, null, 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (227, 220, null, 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (228, 220, null, 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (229, 220, null, 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (230, 220, null, 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (231, 220, null, 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (232, 220, null, 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (233, 220, '$$x_1 = 0.23851648071345$$$$x_2 = -0.83851648071345$$', 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (234, 220, null, 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (235, 220, '$$x_1 = 0$$$$x_2 = -0.6$$', 1, 'x', null);
INSERT INTO edomp_final.problem_final (id, problem_template_id, result, is_generated, variable, first_n) VALUES (236, 220, '$$x_1 = 0.23851648071345$$$$x_2 = -0.83851648071345$$', 1, 'x', null);